### Correct-number
POST http://localhost:6081/customer-insight-platform/phone-number/verify
content-type: application/json
Authorization: fake-token

{
  "phoneNumber" : "07843274323"
}

### Non-numeric
POST http://localhost:6081/customer-insight-platform/phone-number/verify
content-type: application/json
Authorization: fake-token

{
"phoneNumber" : "sajdkl"
}

### Three-digit number
POST http://localhost:6081/customer-insight-platform/phone-number/verify
content-type: application/json
Authorization: fake-token

{
  "phoneNumber" : "999"
}

### 20-digit number
POST http://localhost:6081/customer-insight-platform/phone-number/verify
content-type: application/json
Authorization: fake-token

{
  "phoneNumber" : "0123456786901234567869"
}

### 7-digit number
POST http://localhost:6081/customer-insight-platform/phone-number/verify
content-type: application/json
Authorization: fake-token

{
  "phoneNumber" : "0123456"
}

### Correct number
POST http://localhost:6081/customer-insight-platform/phone-number/verify
content-type: application/json
Authorization: fake-token

{
  "phoneNumber" : "07843274323"
}

### incorrect-number
POST http://localhost:6081/customer-insight-platform/phone-number/verify
content-type: application/json
Authorization: fake-token

{
  "phoneNumber" : "wed"
}


