### Correct-number
POST http://localhost:8080/customer-insight-platform/phone-number/validate-format
content-type: application/json

{
  "phoneNumber" : "07843274323"
}

### Non-numeric
POST http://localhost:8080/customer-insight-platform/phone-number/validate-format
content-type: application/json

{
"phoneNumber" : "sajdkl"
}

### Three-digit number
POST http://localhost:8080/customer-insight-platform/phone-number/validate-format
content-type: application/json

{
  "phoneNumber" : "999"
}

### 20-digit number
POST http://localhost:8080/customer-insight-platform/phone-number/validate-format
content-type: application/json

{
  "phoneNumber" : "0123456786901234567869"
}

### 7-digit number
POST http://localhost:8080/customer-insight-platform/phone-number/validate-format
content-type: application/json

{
  "phoneNumber" : "0123456"
}







